import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

#inputs
inputs = [
    'Text: The Amazon rainforest is the largest tropical rainforest in the world.',
    'Q: Which rainforest is the largest tropical rainforest?',
    'A: The Amazon rainforest is the largest tropical rainforest in the world.',
    'Text: Oxygen is essential for human survival.',
    'Q: What is essential for human survival?',
    'A: Oxygen is essential for human survival.',
    'Text: The Eiffel Tower is located in Paris, France.',
    'Q: Where is the Eiffel Tower located?',
    'A: The Eiffel Tower is located in Paris, France.',
    'Text: The human body has 206 bones.',
    'Q: How many bones does the human body have?',
    'A: The human body has 206 bones.',
    'Text: The Mona Lisa is a famous painting by Leonardo da Vinci.',
    'Q: Who painted the Mona Lisa?',
    'A: The Mona Lisa is a famous painting by Leonardo da Vinci.',
    'Text: The Nile River is the longest river in the world.',
    'Q: Which river is the longest river in the world?',
    'A: The Nile River is the longest river in the world.',
    'Text: The Statue of Liberty is a symbol of freedom.',
    'Q: What does the Statue of Liberty symbolize?',
    'A: The Statue of Liberty is a symbol of freedom.',
    'Text: The Sahara Desert is the largest hot desert in the world.',
    'Q: Which desert is the largest hot desert in the world?',
    'A: The Sahara Desert is the largest hot desert in the world.',
    'Text: Gravity is a force that attracts objects towards each other.',
    'Q: What is gravity?',
    'A: Gravity is a force that attracts objects towards each other.',
    'Text: The Roman Colosseum is an ancient amphitheater.',
    'Q: What is the Roman Colosseum?',
    'A: The Roman Colosseum is an ancient amphitheater.',
    'Text: Photosynthesis is the process by which plants convert sunlight into energy.',
    'Q: What is photosynthesis?',
    'A: Photosynthesis is the process by which plants convert sunlight into energy.',
    'Text: The Pacific Ocean is the largest ocean on Earth.',
    'Q: Which ocean is the largest ocean on Earth?',
    'A: The Pacific Ocean is the largest ocean on Earth.',
    'Text: Albert Einstein was a renowned physicist.',
    'Q: Who was a renowned physicist?',
    'A: Albert Einstein was a renowned physicist.',
    'Text: The Taj Mahal is a mausoleum located in India.',
    'Q: Where is the Taj Mahal located?',
    'A: The Taj Mahal is a mausoleum located in India.',
    'Text: The human brain is responsible for processing information.',
    'Q: What is responsible for processing information in the human body?',
    'A: The human brain is responsible for processing information.',
    'Text: The Arctic is a region located in the northernmost part of the Earth.',
    'Q: Where is the Arctic located?',
    'A: The Arctic is a region located in the northernmost part of the Earth.',
    'Text: William Shakespeare is considered one of the greatest playwrights in history.',
    'Q: Who is considered one of the greatest playwrights in history?',
    'A: William Shakespeare is considered one of the greatest playwrights in history.',
    'Text: The Australian Outback is a vast, remote area in Australia.',
    'Q: What is the Australian Outback?',
    'A: The Australian Outback is a vast, remote area in Australia.',
    'Text: The human heart pumps blood throughout the body.',
    'Q: What is the function of the human heart?',
    'A: The human heart pumps blood throughout the body.',
    'Text: The Andes Mountains are the longest continental mountain range in the world.',
    'Q: Which mountain range is the longest continental mountain range?',
    'A: The Andes Mountains are the longest continental mountain range in the world.',
    'Text: Vincent van Gogh was a famous Dutch painter.',
    'Q: Who was a famous Dutch painter?',
    'A: Vincent van Gogh was a famous Dutch painter.',
    'Text: The Sahara Desert is characterized by its vast stretches of sand dunes.',
    'Q: What is the Sahara Desert characterized by?',
    'A: The Sahara Desert is characterized by its vast stretches of sand dunes.',
    'Text: The human immune system protects the body against diseases.',
    'Q: What is the function of the human immune system?',
    'A: The human immune system protects the body against diseases.',
    'Text: The Mediterranean Sea is a popular tourist destination.',
    'Q: What is the Mediterranean Sea known for?',
    'A: The Mediterranean Sea is known for being a popular tourist destination.',
    'Text: Leonardo da Vinci was a polymath who excelled in various fields.',
    'Q: Who was a polymath who excelled in various fields?',
    'A: Leonardo da Vinci was a polymath who excelled in various fields.',
    'Text: The Great Barrier Reef is the largest coral reef system in the world.',
    'Q: Which coral reef system is the largest in the world?',
    'A: The Great Barrier Reef is the largest coral reef system in the world.',
    'Text: Marie Curie was a pioneering scientist who conducted groundbreaking research on radioactivity.',
    'Q: Who was a pioneering scientist known for research on radioactivity?',
    'A: Marie Curie was a pioneering scientist who conducted groundbreaking research on radioactivity.',
    'Text: The Himalayas are the highest mountain range in the world.',
    'Q: Which mountain range is the highest in the world?',
    'A: The Himalayas are the highest mountain range in the world.',
    'Text: Isaac Newton formulated the laws of motion and universal gravitation.',
    'Q: Who formulated the laws of motion and universal gravitation?',
    'A: Isaac Newton formulated the laws of motion and universal gravitation.',
    'Text: The Serengeti National Park is located in Tanzania.',
    'Q: Where is the Serengeti National Park located?',
    'A: The Serengeti National Park is located in Tanzania.',
    'Text: The human respiratory system is responsible for breathing.',
    'Q: What is responsible for breathing in the human body?',
    'A: The human respiratory system is responsible for breathing.',
    'Text: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Q: Where is the Colosseum located?',
    'A: The Colosseum is located in Rome, Italy.',
    'Text: The theory of evolution was proposed by Charles Darwin.',
    'Q: Who proposed the theory of evolution?',
    'A: The theory of evolution was proposed by Charles Darwin.',
    'Text: The Red Sea is a seawater inlet of the Indian Ocean.',
    'Q: What is the Red Sea?',
    'A: The Red Sea is a seawater inlet of the Indian Ocean.',
    'Text: Jane Austen was a renowned British author known for her novels.',
    'Q: Who was a renowned British author known for her novels?',
    'A: Jane Austen was a renowned British author known for her novels.',
    'Text: The Grand Canyon is a steep-sided canyon located in Arizona, USA.',
    'Q: Where is the Grand Canyon located?',
    'A: The Grand Canyon is located in Arizona, USA.',
    'Text: The theory of relativity was developed by Albert Einstein.',
    'Q: Who developed the theory of relativity?',
    'A: The theory of relativity was developed by Albert Einstein.',
    'Text: The Sydney Opera House is an iconic landmark in Sydney, Australia.',
    'Q: What is the Sydney Opera House?',
    'A: The Sydney Opera House is an iconic landmark in Sydney, Australia.',
    'Text: The concept of gravity was popularized by Sir Isaac Newton.',
    'Q: Who popularized the concept of gravity?',
    'A: The concept of gravity was popularized by Sir Isaac Newton.',
    'Text: The Great Pyramid of Giza is the oldest and largest of the three pyramids in Giza, Egypt.',
    'Q: Which pyramid is the oldest and largest in Giza, Egypt?',
    'A: The Great Pyramid of Giza is the oldest and largest of the three pyramids in Giza, Egypt.',
    'Text: Jane Goodall is a renowned primatologist known for her extensive study of chimpanzees.',
    'Q: Who is a renowned primatologist known for the study of chimpanzees?',
    'A: Jane Goodall is a renowned primatologist known for her extensive study of chimpanzees.',
    'Text: The Great Barrier Reef is home to a diverse array of marine life.',
    'Q: What is the Great Barrier Reef known for?',
    'A: The Great Barrier Reef is known for being home to a diverse array of marine life.',
    'Text: Wolfgang Amadeus Mozart was a prolific and influential composer.',
    'Q: Who was a prolific and influential composer?',
    'A: Wolfgang Amadeus Mozart was a prolific and influential composer.',
    'Text: The Ganges River is considered sacred by Hindus.',
    'Q: Which river is considered sacred by Hindus?',
    'A: The Ganges River is considered sacred by Hindus.',
    'Text: Leonardo da Vinci is famous for his iconic painting, the Mona Lisa.',
    'Q: What is Leonardo da Vinci famous for?',
    'A: Leonardo da Vinci is famous for his iconic painting, the Mona Lisa.',
    'Text: The Great Wall of China is an ancient fortification.',
    'Q: What is the Great Wall of China?',
    'A: The Great Wall of China is an ancient fortification.',
    'Text: The concept of natural selection was proposed by Charles Darwin.',
    'Q: Who proposed the concept of natural selection?',
    'A: The concept of natural selection was proposed by Charles Darwin.',
    'Text: Vincent van Goghs Starry Night is a famous masterpiece.',
    'Q: What is Vincent van Gogh\'s Starry Night?',
    'A: Vincent van Gogh\'s Starry Night is a famous masterpiece.',
    'Text: The Mississippi River is the second-longest river in the United States.',
    'Q: Which river is the second-longest in the United States?',
    'A: The Mississippi River is the second-longest river in the United States.',
    'Text: The theory of general relativity was formulated by Albert Einstein.',
    'Q: Who formulated the theory of general relativity?',
    'A: The theory of general relativity was formulated by Albert Einstein.',
    'Text: The Louvre Museum in Paris houses the famous painting, the Mona Lisa.',
    'Q: What is housed in the Louvre Museum in Paris?',
    'A: The Louvre Museum in Paris houses the famous painting, the Mona Lisa.',
    'Text: The Nile River is associated with ancient Egyptian civilization.',
    'Q: What is the Nile River associated with?',
    'A: The Nile River is associated with ancient Egyptian civilization.',
    'Text: Ludwig van Beethoven was a prominent composer of the classical era.',
    'Q: Who was a prominent composer of the classical era?',
    'A: Ludwig van Beethoven was a prominent composer of the classical era.',
    'Text: The Sahara Desert is the largest hot desert on Earth.',
    'Q: Which desert is the largest hot desert on Earth?',
    'A: The Sahara Desert is the largest hot desert on Earth.',
    'Text: Charles Dickens is considered one of the greatest writers in English literature.',
    'Q: Who is considered one of the greatest writers in English literature?',
    'A: Charles Dickens is considered one of the greatest writers in English literature.',
    'Text: The Tower of London is a historic castle located on the banks of the River Thames.',
    'Q: What is the Tower of London?',
    'A: The Tower of London is a historic castle located on the banks of the River Thames.',
    'Text: The concept of quantum mechanics revolutionized our understanding of the microscopic world.',
    'Q: What revolutionized our understanding of the microscopic world?',
    'A: The concept of quantum mechanics revolutionized our understanding of the microscopic world.',
    'Text: The Galapagos Islands are famous for their unique wildlife.',
    'Q: What are the Galapagos Islands famous for?',
    'A: The Galapagos Islands are famous for their unique wildlife.',
    'Text: Ernest Hemingway was a celebrated American writer and journalist.',
    'Q: Who was a celebrated American writer and journalist?',
    'A: Ernest Hemingway was a celebrated American writer and journalist.',
    'Text: The Great Sphinx of Giza is an iconic ancient Egyptian statue.',
    'Q: What is the Great Sphinx of Giza?',
    'A: The Great Sphinx of Giza is an iconic ancient Egyptian statue.',
    'Text: Wolfgang Amadeus Mozart composed over 600 works, including symphonies, concertos, and operas.',
    'Q: How many works did Wolfgang Amadeus Mozart compose?',
    'A: Wolfgang Amadeus Mozart composed over 600 works, including symphonies, concertos, and operas.',
    'Text: The Dead Sea is known for its high salt concentration, which allows swimmers to float effortlessly.',
    'Q: What is the Dead Sea known for?',
    'A: The Dead Sea is known for its high salt concentration, which allows swimmers to float effortlessly.',
    'Text: J.K. Rowling is the author of the Harry Potter book series.',
    'Q: Who is the author of the Harry Potter book series?',
    'A: J.K. Rowling is the author of the Harry Potter book series.',
    'Text: The Rocky Mountains are a major mountain range in western North America.',
    'Q: What is the Rocky Mountains?',
    'A: The Rocky Mountains are a major mountain range in western North America.',
    'Text: The concept of black holes was proposed by Albert Einstein.',
    'Q: Who proposed the concept of black holes?',
    'A: The concept of black holes was proposed by Albert Einstein.',
    'Text: The Sistine Chapel is a famous chapel in the Apostolic Palace, Vatican City.',
    'Q: Where is the Sistine Chapel located?',
    'A: The Sistine Chapel is located in the Apostolic Palace, Vatican City.',
    'Text: William Shakespeare is widely regarded as the greatest playwright in the English language.',
    'Q: Who is widely regarded as the greatest playwright in the English language?',
    'A: William Shakespeare is widely regarded as the greatest playwright in the English language.',
    'Text: The Eiffel Tower is an iconic landmark in Paris, France.',
    'Q: What is the Eiffel Tower?',
    'A: The Eiffel Tower is an iconic landmark in Paris, France.',
    'Text: The concept of DNA structure and its role in genetics was discovered by James Watson and Francis Crick.',
    'Q: Who discovered the concept of DNA structure and its role in genetics?',
    'A: The concept of DNA structure and its role in genetics was discovered by James Watson and Francis Crick.',
    'Text: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Q: What is the Taj Mahal?',
    'A: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Q: What is Beethoven\'s Symphony No. 9 renowned for?',
    'A: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Text: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Q: Which rainforest is the largest tropical rainforest in the world?',
    'A: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Text: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Q: Who described the concept of inertia?',
    'A: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Text: The Statue of Liberty is a symbol of freedom and democracy.',
    'Q: What is the Statue of Liberty?',
    'A: The Statue of Liberty is a symbol of freedom and democracy.',
    'Text: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Q: Who developed the concept of the periodic table of elements?',
    'A: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Text: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Q: What is the Colosseum?',
    'A: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Text: The concept of natural rights was influential in the development of modern political philosophy.',
    'Q: What was influential in the development of modern political philosophy?',
    'A: The concept of natural rights was influential in the development of modern political philosophy.',
    'Text: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Q: What is the Golden Gate Bridge?',
    'A: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Text: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Q: What does the concept of photosynthesis explain?',
    'A: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Text: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Q: What is the Colosseum?',
    'A: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Q: What is the Golden Gate Bridge?',
    'A: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Text: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Q: What does the concept of photosynthesis explain?',
    'A: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Text: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Q: What is the Taj Mahal?',
    'A: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Text: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Q: What is Beethoven\'s Symphony No. 9 renowned for?',
    'A: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Text: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Q: Which rainforest is the largest tropical rainforest in the world?',
    'A: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Text: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Q: Who described the concept of inertia?',
    'A: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Text: The Statue of Liberty is a symbol of freedom and democracy.',
    'Q: What is the Statue of Liberty?',
    'A: The Statue of Liberty is a symbol of freedom and democracy.',
    'Text: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Q: Who developed the concept of the periodic table of elements?',
    'A: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Text: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Q: What is the Colosseum?',
    'A: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Text: The concept of natural rights was influential in the development of modern political philosophy.',
    'Q: What was influential in the development of modern political philosophy?',
    'A: The concept of natural rights was influential in the development of modern political philosophy.',
    'Text: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Q: What is the Golden Gate Bridge?',
    'A: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Text: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Q: What does the concept of photosynthesis explain?',
    'A: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Text: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Q: What is the Taj Mahal?',
    'A: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Text: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Q: What is Beethoven\'s Symphony No. 9 renowned for?',
    'A: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Text: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Q: Which rainforest is the largest tropical rainforest in the world?',
    'A: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Text: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Q: Who described the concept of inertia?',
    'A: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Text: The Statue of Liberty is a symbol of freedom and democracy.',
    'Q: What is the Statue of Liberty?',
    'A: The Statue of Liberty is a symbol of freedom and democracy.',
    'Text: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Q: Who developed the concept of the periodic table of elements?',
    'A: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Text: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Q: What is the Colosseum?',
    'A: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Text: The concept of natural rights was influential in the development of modern political philosophy.',
    'Q: What was influential in the development of modern political philosophy?',
    'A: The concept of natural rights was influential in the development of modern political philosophy.',
    'Text: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Q: What is the Golden Gate Bridge?',
    'A: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Text: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Q: What does the concept of photosynthesis explain?',
    'A: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Text: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Q: What is the Taj Mahal?',
    'A: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Text: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Q: What is Beethoven\'s Symphony No. 9 renowned for?',
    'A: Beethoven\'s Symphony No. 9 is renowned for its "Ode to Joy" melody.',
    'Text: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Q: Which rainforest is the largest tropical rainforest in the world?',
    'A: The Amazon Rainforest is the largest tropical rainforest in the world.',
    'Text: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Q: Who described the concept of inertia?',
    'A: The concept of inertia was described by Sir Isaac Newton in his first law of motion.',
    'Text: The Statue of Liberty is a symbol of freedom and democracy.',
    'Q: What is the Statue of Liberty?',
    'A: The Statue of Liberty is a symbol of freedom and democracy.',
    'Text: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Q: Who developed the concept of the periodic table of elements?',
    'A: The concept of the periodic table of elements was developed by Dmitri Mendeleev.',
    'Text: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Q: What is the Colosseum?',
    'A: The Colosseum in Rome, Italy, is an ancient amphitheater.',
    'Text: The concept of natural rights was influential in the development of modern political philosophy.',
    'Q: What was influential in the development of modern political philosophy?',
    'A: The concept of natural rights was influential in the development of modern political philosophy.',
    'Text: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Q: What is the Golden Gate Bridge?',
    'A: The Golden Gate Bridge is an iconic suspension bridge in San Francisco, California.',
    'Text: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Q: What does the concept of photosynthesis explain?',
    'A: The concept of photosynthesis explains how plants convert sunlight into energy.',
    'Text: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Q: What is the Taj Mahal?',
    'A: The Taj Mahal is a UNESCO World Heritage Site and a symbol of love.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: The Great Wall of China is a famous historical landmark.',
    'Q: What is the Great Wall of China?',
    'A: The Great Wall of China is a famous historical landmark.',
    'Text: Water boils at 100 degrees Celsius.',
    'Q: At what temperature does water boil?',
    'A: Water boils at 100 degrees Celsius.',
    'Text: Mount Everest is the highest peak in the world.',
    'Q: Which is the highest peak in the world?',
    'A: Mount Everest is the highest peak in the world.',
    'Text: Cats are known for their fur',
    'Q: What are cats known for?',
    'A: Cats are known for their fur.',
    'Text: The Mona Lisa is a famous portrait painted by Leonardo da Vinci.',
    'Q: Who painted the Mona Lisa?',
    'A: The Mona Lisa was painted by Leonardo da Vinci.',
    'Text: Gravity is the force that attracts objects toward each other.',
    'Q: What is gravity?',
    'A: Gravity is the force that attracts objects toward each other.',
    'Text: The Great Barrier Reef is the largest coral reef system in the world.',
    'Q: Which is the largest coral reef system in the world?',
    'A: The Great Barrier Reef is the largest coral reef system in the world.',
    'Text: The concept of natural selection is central to the theory of evolution.',
    'Q: What is central to the theory of evolution?',
    'A: The concept of natural selection is central to the theory of evolution.',
    'Text: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Q: What are the pyramids of Egypt?',
    'A: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Text: Oxygen is essential for the survival of most living organisms.',
    'Q: What is essential for the survival of most living organisms?',
    'A: Oxygen is essential for the survival of most living organisms.',
    'Text: The theory of relativity was developed by Albert Einstein.',
    'Q: Who developed the theory of relativity?',
    'A: The theory of relativity was developed by Albert Einstein.',
    'Text: The Eiffel Tower is a famous landmark in Paris, France.',
    'Q: What is the Eiffel Tower?',
    'A: The Eiffel Tower is a famous landmark in Paris, France.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: The Great Wall of China is a famous historical landmark.',
    'Q: What is the Great Wall of China?',
    'A: The Great Wall of China is a famous historical landmark.',
    'Text: Water boils at 100 degrees Celsius.',
    'Q: At what temperature does water boil?',
    'A: Water boils at 100 degrees Celsius.',
    'Text: Mount Everest is the highest peak in the world.',
    'Q: Which is the highest peak in the world?',
    'A: Mount Everest is the highest peak in the world.',
    'Text: Cats are known for their fur',
    'Q: What are cats known for?',
    'A: Cats are known for their fur.',
    'Text: The Mona Lisa is a famous portrait painted by Leonardo da Vinci.',
    'Q: Who painted the Mona Lisa?',
    'A: The Mona Lisa was painted by Leonardo da Vinci.',
    'Text: Gravity is the force that attracts objects toward each other.',
    'Q: What is gravity?',
    'A: Gravity is the force that attracts objects toward each other.',
    'Text: The Great Barrier Reef is the largest coral reef system in the world.',
    'Q: Which is the largest coral reef system in the world?',
    'A: The Great Barrier Reef is the largest coral reef system in the world.',
    'Text: The concept of natural selection is central to the theory of evolution.',
    'Q: What is central to the theory of evolution?',
    'A: The concept of natural selection is central to the theory of evolution.',
    'Text: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Q: What are the pyramids of Egypt?',
    'A: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Text: Oxygen is essential for the survival of most living organisms.',
    'Q: What is essential for the survival of most living organisms?',
    'A: Oxygen is essential for the survival of most living organisms.',
    'Text: The theory of relativity was developed by Albert Einstein.',
    'Q: Who developed the theory of relativity?',
    'A: The theory of relativity was developed by Albert Einstein.',
    'Text: The Eiffel Tower is a famous landmark in Paris, France.',
    'Q: What is the Eiffel Tower?',
    'A: The Eiffel Tower is a famous landmark in Paris, France.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: The Great Wall of China is a famous historical landmark.',
    'Q: What is the Great Wall of China?',
    'A: The Great Wall of China is a famous historical landmark.',
    'Text: Water boils at 100 degrees Celsius.',
    'Q: At what temperature does water boil?',
    'A: Water boils at 100 degrees Celsius.',
    'Text: Mount Everest is the highest peak in the world.',
    'Q: Which is the highest peak in the world?',
    'A: Mount Everest is the highest peak in the world.',
    'Text: Cats are known for their fur',
    'Q: What are cats known for?',
    'A: Cats are known for their fur.',
    'Text: The Mona Lisa is a famous portrait painted by Leonardo da Vinci.',
    'Q: Who painted the Mona Lisa?',
    'A: The Mona Lisa was painted by Leonardo da Vinci.',
    'Text: Gravity is the force that attracts objects toward each other.',
    'Q: What is gravity?',
    'A: Gravity is the force that attracts objects toward each other.',
    'Text: The Great Barrier Reef is the largest coral reef system in the world.',
    'Q: Which is the largest coral reef system in the world?',
    'A: The Great Barrier Reef is the largest coral reef system in the world.',
    'Text: The concept of natural selection is central to the theory of evolution.',
    'Q: What is central to the theory of evolution?',
    'A: The concept of natural selection is central to the theory of evolution.',
    'Text: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Q: What are the pyramids of Egypt?',
    'A: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Text: Oxygen is essential for the survival of most living organisms.',
    'Q: What is essential for the survival of most living organisms?',
    'A: Oxygen is essential for the survival of most living organisms.',
    'Text: The theory of relativity was developed by Albert Einstein.',
    'Q: Who developed the theory of relativity?',
    'A: The theory of relativity was developed by Albert Einstein.',
    'Text: The Eiffel Tower is a famous landmark in Paris, France.',
    'Q: What is the Eiffel Tower?',
    'A: The Eiffel Tower is a famous landmark in Paris, France.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: The Great Wall of China is a famous historical landmark.',
    'Q: What is the Great Wall of China?',
    'A: The Great Wall of China is a famous historical landmark.',
    'Text: Water boils at 100 degrees Celsius.',
    'Q: At what temperature does water boil?',
    'A: Water boils at 100 degrees Celsius.',
    'Text: Mount Everest is the highest peak in the world.',
    'Q: Which is the highest peak in the world?',
    'A: Mount Everest is the highest peak in the world.',
    'Text: Cats are known for their fur',
    'Q: What are cats known for?',
    'A: Cats are known for their fur.',
    'Text: The Mona Lisa is a famous portrait painted by Leonardo da Vinci.',
    'Q: Who painted the Mona Lisa?',
    'A: The Mona Lisa was painted by Leonardo da Vinci.',
    'Text: Gravity is the force that attracts objects toward each other.',
    'Q: What is gravity?',
    'A: Gravity is the force that attracts objects toward each other.',
    'Text: The Great Barrier Reef is the largest coral reef system in the world.',
    'Q: Which is the largest coral reef system in the world?',
    'A: The Great Barrier Reef is the largest coral reef system in the world.',
    'Text: The concept of natural selection is central to the theory of evolution.',
    'Q: What is central to the theory of evolution?',
    'A: The concept of natural selection is central to the theory of evolution.',
    'Text: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Q: What are the pyramids of Egypt?',
    'A: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Text: Oxygen is essential for the survival of most living organisms.',
    'Q: What is essential for the survival of most living organisms?',
    'A: Oxygen is essential for the survival of most living organisms.',
    'Text: The theory of relativity was developed by Albert Einstein.',
    'Q: Who developed the theory of relativity?',
    'A: The theory of relativity was developed by Albert Einstein.',
    'Text: The Eiffel Tower is a famous landmark in Paris, France.',
    'Q: What is the Eiffel Tower?',
    'A: The Eiffel Tower is a famous landmark in Paris, France.',
    'Text: The concept of supply and demand is a fundamental principle in economics.',
    'Q: What is a fundamental principle in economics?',
    'A: The concept of supply and demand is a fundamental principle in economics.',
    'Text: The Great Wall of China is a famous historical landmark.',
    'Q: What is the Great Wall of China?',
    'A: The Great Wall of China is a famous historical landmark.',
    'Text: Water boils at 100 degrees Celsius.',
    'Q: At what temperature does water boil?',
    'A: Water boils at 100 degrees Celsius.',
    'Text: Mount Everest is the highest peak in the world.',
    'Q: Which is the highest peak in the world?',
    'A: Mount Everest is the highest peak in the world.',
    'Text: Cats are known for their fur',
    'Q: What are cats known for?',
    'A: Cats are known for their fur.',
    'Text: The Mona Lisa is a famous portrait painted by Leonardo da Vinci.',
    'Q: Who painted the Mona Lisa?',
    'A: The Mona Lisa was painted by Leonardo da Vinci.',
    'Text: Gravity is the force that attracts objects toward each other.',
    'Q: What is gravity?',
    'A: Gravity is the force that attracts objects toward each other.',
    'Text: The Great Barrier Reef is the largest coral reef system in the world.',
    'Q: Which is the largest coral reef system in the world?',
    'A: The Great Barrier Reef is the largest coral reef system in the world.',
    'Text: The concept of natural selection is central to the theory of evolution.',
    'Q: What is central to the theory of evolution?',
    'A: The concept of natural selection is central to the theory of evolution.',
    'Text: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Q: What are the pyramids of Egypt?',
    'A: The pyramids of Egypt are ancient structures built as tombs for pharaohs.',
    'Text: Oxygen is essential for the survival of most living organisms.',
    'Q: What is essential for the survival of most living organisms?',
    'A: Oxygen is essential for the survival of most living organisms.',
    'Text: The theory of relativity was developed by Albert Einstein.',
    'Q: Who developed the theory of relativity?',
    'A: The theory of relativity was developed by Albert Einstein.',
    'Text: The Eiffel Tower is a famous landmark in Paris, France.',
    'Q: What is the Eiffel Tower?',
    'A: The Eiffel Tower is an iconic landmark in Paris, France.',
    'Text: There are various breeds of cats, including Persian, Siamese, and Maine Coon.',
    'Q: Name some cat breeds.',
    'A: Some cat breeds include Persian, Siamese, and Maine Coon.',
    'Text: Cats have a highly developed sense of hearing and night vision.',
    'Q: What are some special abilities of cats?',
    'A: Cats have a highly developed sense of hearing and night vision.',
    'Text: Cats are known for their independent nature and agility.',
    'Q: What are some characteristics of cats?',
    'A: Cats are known for their independent nature and agility.',
    'Text: Domestic cats are descendants of wildcats that were domesticated thousands of years ago.',
    'Q: How did domestic cats originate?',
    'A: Domestic cats are descendants of wildcats that were domesticated thousands of years ago.',
    'Text: Cats are popular as companions and are valued for their companionship and affection.',
    'Q: Why are cats popular as pets?',
    'A: Cats are popular as companions and are valued for their companionship and affection.',
    'Text: Cats communicate through a combination of vocalizations, body language, and scent marking.',
    'Q: How do cats communicate?',
    'A: Cats communicate through a combination of vocalizations, body language, and scent marking.',
    'Text: Gabriel is desperate because this model is not working',
    'Q: Why is Gabriel desperate?',
    'A: Because the model is not working',
    'Text: Gabriel is beatiful because Marisol think so',
    'Q: Why is Gabriel beatiful?',
    'A: Because Marisol think so',
    'Text: Gabriel is good',
    'Q: Is gabriel Good?',
    'A: Yes',
    'Text: Gabriel is good',
    'Q: Is Gabriel bad?',
    'A: No, is good',
    'Text: the Cat is good',
    'Q: Is the Cat bad?',
    'A: No, he is good',
    'Text: the Dog is good',
    'Q: Is the Dog Good?',
    'A: Yes',
    'Text: the Food is good',
    'Q: Is the Food bad?',
    'A: No, the food is good',
    'Text: the Cat is good',
    'Q: Is the Cat bad?',
    'A: No, the cat is good',
    'Text: Maria is good',
    'Q: Is Maria bad?',
    'A: No, Maria is good',
    'Text: Maria is a good cooker',
    'Q: Is Maria a good cooker?',
    'A: Yes',
    'Text: Tigers are bad companions',
    'Q: Are Tigers bad companions?',
    'A: Yes',
    'Text: Maria is a good cooker',
    'Q: Is Maria a bad cooker?',
    'A: No she is a good cooker',
    'Text: Tigers are bad companions',
    'Q: Are Tigers good companions?',
    'A: No they are bad companions',
    'Text: Otters are good companions',
    'Q: Are otters good companions?',
    'A: Yes',
    'Text: Capybaras are good companions',
    'Q: Are Capybaras good companions?',
    'A: Yes',
    'Text: Capybaras are bad companions',
    'Q: Are Capybaras bad companions?',
    'A: Yes',
    'Text: Ducks are good companions',
    'Q: Are Ducks good companions?',
    'A: Yes',
    'Text: Dogs are good companions',
    'Q: Are Dogs good companions?',
    'A: Yes',
    'Text: Animals are usually good',
    'Q: Are Animals usually good?',
    'A: Yes',
    'Text: Gabriel loves Coyoli',
    'Q: Gabriel loves Coyoli?',
    'A: Yes',
]
# Separate the inputs into T , Q AND A, text question awnser
texts = []
questions = []
answers = []
for input_str in inputs:
    if input_str.startswith('Text:'):
        texts.append(input_str.replace('Text:', '').strip())
    elif input_str.startswith('Q:'):
        questions.append(input_str.replace('Q:', '').strip())
    elif input_str.startswith('A:'):
        answers.append(input_str.replace('A:', '').strip())

# Tokenize TQA
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts + questions + answers)
num_words = len(tokenizer.word_index) + 1

# Encode TQA into sequences
text_sequences = tokenizer.texts_to_sequences(texts)
question_sequences = tokenizer.texts_to_sequences(questions)
answer_sequences = tokenizer.texts_to_sequences(answers)

# Pad the sequences to a fixed length
max_length = max(max(len(seq) for seq in text_sequences),
                 max(len(seq) for seq in question_sequences),
                 max(len(seq) for seq in answer_sequences))
text_sequences = pad_sequences(text_sequences, maxlen=max_length, padding='post')
question_sequences = pad_sequences(question_sequences, maxlen=max_length, padding='post')
answer_sequences = pad_sequences(answer_sequences, maxlen=max_length, padding='post')

# Define the model architecture
input_text = keras.Input(shape=(max_length,))
input_question = keras.Input(shape=(max_length,))
embedding = keras.layers.Embedding(num_words, 100)
embedded_text = embedding(input_text)
embedded_question = embedding(input_question)
concatenated = keras.layers.Concatenate()([embedded_text, embedded_question])
dense = keras.layers.Dense(128, activation='relu')
output = dense(concatenated)
output = keras.layers.Dense(num_words, activation='softmax')(output)
model = keras.Model([input_text, input_question], output)

# Compiling and training the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit([text_sequences, question_sequences], answer_sequences, epochs=300, verbose=2)

# Testing the model
test_text = ''
test_question = ''
test_text_sequence = tokenizer.texts_to_sequences([test_text])
test_question_sequence = tokenizer.texts_to_sequences([test_question])
test_text_sequence = pad_sequences(test_text_sequence, maxlen=max_length, padding='post')
test_question_sequence = pad_sequences(test_question_sequence, maxlen=max_length, padding='post')
predicted_answer_sequence = model.predict([test_text_sequence, test_question_sequence])
predicted_answer = ' '.join(tokenizer.index_word[index] for index in tf.argmax(predicted_answer_sequence, axis=2).numpy()[0] if index != 0)
predicted_answer = predicted_answer.replace(' <pad>', '')
print('Predicted answer:', predicted_answer)